### ISSUE TITLE
Error in module asyncio.run(main())

### ISSUE THREAD

**Issue by davidKooreman** [jagheterfredrik/wallbox-pwn#10]
Sending pwnware
Pwnware was received by Wallbox
Traceback (most recent call last):
  File "C:\wallbox-pwn\wallbox-pwn.py", line 149, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\wallbox-pwn\wallbox-pwn.py", line 135, in main
    hup_data = await wb.execute("r_hup")
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\wallbox-pwn\wallbox-pwn.py", line 79, in execute
    await self.client.write_gatt_char(self.rx_char, chunk, self.device_definition.write_response)
  File "C:\Program Files\Python312\Lib\site-packages\bleak\__init__.py", line 776, in write_gatt_char
    await self._backend.write_gatt_char(characteristic, data, response)
  File "C:\Program Files\Python312\Lib\site-packages\bleak\backends\winrt\client.py", line 887, in write_gatt_char
    raise BleakError("Not connected")
bleak.exc.BleakError: Not connected

**Comment by jagheterfredrik** [comment]
Bluetooth lost connection, try again perhaps with another computer or Bluetooth dongle

**Comment by davidKooreman** [comment]
Thanks ill try

Op za 13 apr. 2024 11:48 schreef Fredrik Gustafsson <
***@***.***>:

**Comment by davidKooreman** [comment]
Update succeeded. Now see if the wallbox mqqt software is stable.

Thanks for the advice

Op za 13 apr. 2024 12:54 schreef David Kooreman ***@***.***>:
