### ISSUE TITLE
fails after selecting device

### ISSUE THREAD

**Issue by peepsnet** [jagheterfredrik/wallbox-pwn#17]
python wallbox-pwn.py
Please choose Wallbox:
0) WB921406 (A4:9E:69:64:12:33)
> 0
Traceback (most recent call last):
  File "/root/wallbox.pwn/wallbox-pwn.py", line 149, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/root/wallbox.pwn/wallbox-pwn.py", line 102, in main
    await wb.connect(wallboxes[chosen_idx])
  File "/root/wallbox.pwn/wallbox-pwn.py", line 36, in connect
    await self.client.connect()
  File "/usr/local/lib/python3.9/dist-packages/bleak/__init__.py", line 615, in connect
    return await self._backend.connect(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/bleak/backends/bluezdbus/client.py", line 184, in connect
    watcher = manager.add_device_watcher(
  File "/usr/local/lib/python3.9/dist-packages/bleak/backends/bluezdbus/manager.py", line 613, in add_device_watcher
    self._check_device(device_path)
  File "/usr/local/lib/python3.9/dist-packages/bleak/backends/bluezdbus/manager.py", line 217, in _check_device
    raise BleakError(f"device '{device_path.split('/')[-1]}' not found")
bleak.exc.BleakError: device 'dev_A4_9E_69_64_12_33' not found

I am using a RPI 3 I belive
I download just the wallbox-pwn.py file and the "pip install bleak".
And the Wallbox is from FPL(Florida Power and light) 
https://www.fpl.com/electric-vehicles/evolution/home.html
example: https://www.reddit.com/r/TeslaModelY/comments/156jm2v/fpl_evolution_charger/

EDIT:
I just checked and the charger firmware is 6.6.2 so that must be my issue...
Any chance it can work in the furute?
and
Is there a way I can send a reboot command through the BLE?
because the charger keeps droping the wifi...

UPDATE:   used python3 and got farther... No I need to DL the tar
 python3 wallbox-pwn.py
Please choose Wallbox:
0) WB921406 (A4:9E:69:64:12:33)
> 0
Identified Bluetooth chip: BGX
Setting Wallbox to AP mode
Traceback (most recent call last):
  File "/root/wallbox.pwn/wallbox-pwn.py", line 150, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/root/wallbox.pwn/wallbox-pwn.py", line 112, in main
    payload = open("pwnware.tar", "rb").read()
FileNotFoundError: [Errno 2] No such file or directory: 'pwnware.tar'
root@planespotter:~/wallbox.pwn#

UPDATE: after downloading the tar file

 python3 wallbox-pwn.py
Please choose Wallbox:
0) WB921406 (A4:9E:69:64:12:33)
> 0
Identified Bluetooth chip: BGX
Setting Wallbox to AP mode
Failed to set Wallbox to AP mode

UPDATE:
I get all the way to setting to AP mode.
I am able to see the WIFI SSID and connect to it. 
after pressing enter the firmware is uploaded.
says "Pwnware was received by Wallbox"

but goes no further. 

never gets to:
## Wait for Wallbox to process pwnware
    while True:
        hup_data = await wb.execute("r_hup")
        if hup_data.get('st') == "proc":
            print("Wallbox is processing pwnware...")
            break
        await asyncio.sleep(2)
    while True:
        hup_data = await wb.execute("r_hup")
        if hup_data.get('st') == "done":
            print("Wallbox was pwnd successfully!")
            break
        await asyncio.sleep(2)

Just saw the closed issue:
https://github.com/jagheterfredrik/wallbox-pwn/issues/15

So it is the SW version mismatch!!

**Comment by peepsnet** [comment]
https://github.com/jagheterfredrik/wallbox-pwn/issues/15

**Comment by ryanjjennings** [comment]
I had trouble with it getting stuck even on version 5 fw.  It would get as far as telling me to connect to the AP, but wouldn't ever complete.  I ended up resetting to factory defaults to get it to forget my ssid.  I wonder if it is bad to connect it to home wifi before attempting pwn?
